/// Flutter icons Qibla
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Qibla
///      fonts:
///       - asset: fonts/Qibla.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Qibla {
  Qibla._();

  static const _kFontFam = 'Qibla';

  static const IconData allah = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dua = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData tasbih = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData quran = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData mosque = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ramadan = const IconData(0xe805, fontFamily: _kFontFam);
}
